version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Verander dit naar je frontend directory
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Verander dit naar je backend directory
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
